
lista_ant_sala=[
    ["1. Încălzire articulara","2. Bandă 10 minute",
     "3. Fandari pe loc cu greutăți fără pauza continui Ridicări de picioare la bancă pentru abdomen 4x12x12",
     "4. Indreptări românești cu ganterele fără pauza aparatul de tractiuni la helcometru 4x12x12",
    "5. Hiperextensii pentru fesieri fara pauza continui presa piept 4x12x15 repetari",
    "6. Adductori Plus abductori 4x12x12"
    "7. Banda 25 min."],
    ["1. Încălzire articulara", "2. Bandă 10 minute",
     "3. Fandari pe loc cu greutăți fără pauza continui Ridicări de picioare la bancă pentru abdomen 4x12x12",
     "4. Indreptări românești cu ganterele fără pauza aparatul de tractiuni la helcometru 4x12x12",
     "5. Hiperextensii pentru fesieri fara pauza continui presa piept 4x12x15 repetari",
     "6. Adductori Plus abductori 4x12x12"
     "7. Banda 25 min."],
    ["1. Încălzire articulara", "2. Bandă 10 minute",
     "3. Fandari pe loc cu greutăți fără pauza continui Ridicări de picioare la bancă pentru abdomen 4x12x12",
     "4. Indreptări românești cu ganterele fără pauza aparatul de tractiuni la helcometru 4x12x12",
     "5. Hiperextensii pentru fesieri fara pauza continui presa piept 4x12x15 repetari",
     "6. Adductori Plus abductori 4x12x12"
     "7. Banda 25 min."],
    ["1. Încălzire articulara","2. Bandă 10 minute",
     "3. Fandari pe loc cu greutăți fără pauza continui Ridicări de picioare la bancă pentru abdomen 4x12x12",
     "4. Indreptări românești cu ganterele fără pauza aparatul de tractiuni la helcometru 4x12x12",
    "5. Hiperextensii pentru fesieri fara pauza continui presa piept 4x12x15 repetari",
    "6. Adductori Plus abductori 4x12x12"
    "7. Banda 25 min."],
    ["1. Încălzire articulara","2. Bandă 10 minute",
     "3. Fandari pe loc cu greutăți fără pauza continui Ridicări de picioare la bancă pentru abdomen 4x12x12",
     "4. Indreptări românești cu ganterele fără pauza aparatul de tractiuni la helcometru 4x12x12",
    "5. Hiperextensii pentru fesieri fara pauza continui presa piept 4x12x15 repetari",
    "6. Adductori Plus abductori 4x12x12"
    "7. Banda 25 min."]
]
lista_ant_acasa=[
                ["1. Încălzire articulara, 2. Încălzire cardio vasculara 20\' High knee + 40\' lovirea sezutei, pauză de 30 de secunde si repeți asta de 4 ori",
                 "3. Genuflexiuni cu bara 5x10 (Faci doua serii de încălzire, pe care nu le pui la număr, prima cu propria greutate 20 de repetari, a doua cu 10 kg in spate, mărești treptat greutate si începi sa faci cele 5 serii cu greutate, pana cand la ultimele serii lucrezi cu o greutate ce nu iti permite mai mult de 10 repetari)",
                 "4. Fandari cu gantere 4x10 ( individual cu fiecare picior si treci la celălat dupa ce ai facut 10 repetari, genunchiul din fata nu trece de nivelul vărfurilor degetelor de la picioare, genunchiul din spate coboară drept sub nivelul corpului)",
                 "5. Îndreptări românești pentru bicepsul femural cu bara(partea din spate a coapsei) 4x10(Picioarele la nivelul umerilor, genunchii putin flexati, spatele drept! )",
                 "6. Crunch uri cu discul 4x10",
                 "7. Ridicări de picioare din culcat 5x10-15",
                 "8. Streching"],
                 ["1. Încălzire articulara, 2. Încălzire cardio vasculara 20\' High knee + 40\' lovirea sezutei, pauză de 30 de secunde si repeți asta de 4 ori",
                 "3. Genuflexiuni cu bara 5x10 (Faci doua serii de încălzire, pe care nu le pui la număr, prima cu propria greutate 20 de repetari, a doua cu 10 kg in spate, mărești treptat greutate si începi sa faci cele 5 serii cu greutate, pana cand la ultimele serii lucrezi cu o greutate ce nu iti permite mai mult de 10 repetari)",
                 "4. Fandari cu gantere 4x10 ( individual cu fiecare picior si treci la celălat dupa ce ai facut 10 repetari, genunchiul din fata nu trece de nivelul vărfurilor degetelor de la picioare, genunchiul din spate coboară drept sub nivelul corpului)",
                 "5. Îndreptări românești pentru bicepsul femural cu bara(partea din spate a coapsei) 4x10(Picioarele la nivelul umerilor, genunchii putin flexati, spatele drept! )",
                 "6. Crunch uri cu discul 4x10",
                 "7. Ridicări de picioare din culcat 5x10-15",
                 "8. Streching"],
                 ["1. Încălzire articulara, 2. Încălzire cardio vasculara 20\' High knee + 40\' lovirea sezutei, pauză de 30 de secunde si repeți asta de 4 ori",
                 "3. Genuflexiuni cu bara 5x10 (Faci doua serii de încălzire, pe care nu le pui la număr, prima cu propria greutate 20 de repetari, a doua cu 10 kg in spate, mărești treptat greutate si începi sa faci cele 5 serii cu greutate, pana cand la ultimele serii lucrezi cu o greutate ce nu iti permite mai mult de 10 repetari)",
                 "4. Fandari cu gantere 4x10 ( individual cu fiecare picior si treci la celălat dupa ce ai facut 10 repetari, genunchiul din fata nu trece de nivelul vărfurilor degetelor de la picioare, genunchiul din spate coboară drept sub nivelul corpului)",
                 "5. Îndreptări românești pentru bicepsul femural cu bara(partea din spate a coapsei) 4x10(Picioarele la nivelul umerilor, genunchii putin flexati, spatele drept! )",
                 "6. Crunch uri cu discul 4x10",
                 "7. Ridicări de picioare din culcat 5x10-15",
                 "8. Streching"],
                 ["1. Încălzire articulara, 2. Încălzire cardio vasculara 20\' High knee + 40\' lovirea sezutei, pauză de 30 de secunde si repeți asta de 4 ori",
                 "3. Genuflexiuni cu bara 5x10 (Faci doua serii de încălzire, pe care nu le pui la număr, prima cu propria greutate 20 de repetari, a doua cu 10 kg in spate, mărești treptat greutate si începi sa faci cele 5 serii cu greutate, pana cand la ultimele serii lucrezi cu o greutate ce nu iti permite mai mult de 10 repetari)",
                 "4. Fandari cu gantere 4x10 ( individual cu fiecare picior si treci la celălat dupa ce ai facut 10 repetari, genunchiul din fata nu trece de nivelul vărfurilor degetelor de la picioare, genunchiul din spate coboară drept sub nivelul corpului)",
                 "5. Îndreptări românești pentru bicepsul femural cu bara(partea din spate a coapsei) 4x10(Picioarele la nivelul umerilor, genunchii putin flexati, spatele drept! )",
                 "6. Crunch uri cu discul 4x10",
                 "7. Ridicări de picioare din culcat 5x10-15",
                 "8. Streching"],
                 ["1. Încălzire articulara, 2. Încălzire cardio vasculara 20\' High knee + 40\' lovirea sezutei, pauză de 30 de secunde si repeți asta de 4 ori",
                 "3. Genuflexiuni cu bara 5x10 (Faci doua serii de încălzire, pe care nu le pui la număr, prima cu propria greutate 20 de repetari, a doua cu 10 kg in spate, mărești treptat greutate si începi sa faci cele 5 serii cu greutate, pana cand la ultimele serii lucrezi cu o greutate ce nu iti permite mai mult de 10 repetari)",
                 "4. Fandari cu gantere 4x10 ( individual cu fiecare picior si treci la celălat dupa ce ai facut 10 repetari, genunchiul din fata nu trece de nivelul vărfurilor degetelor de la picioare, genunchiul din spate coboară drept sub nivelul corpului)",
                 "5. Îndreptări românești pentru bicepsul femural cu bara(partea din spate a coapsei) 4x10(Picioarele la nivelul umerilor, genunchii putin flexati, spatele drept! )",
                 "6. Crunch uri cu discul 4x10",
                 "7. Ridicări de picioare din culcat 5x10-15",
                 "8. Streching"]
]
